#requires -Version 7
<#
  Wires every harness to ~/agent-core.

  Claude Code and omp resolve `@~/path` imports natively (verified), so they get
  a thin stub that imports core/ directly - no generated copy to drift.

  Every harness therefore reads core/ directly. Nothing is generated, so there is
  no copy that can drift.
#>
[CmdletBinding()]
param(
  [switch]$WhatIf,
  [ValidateSet('claude', 'omp')]
  [string[]]$Only
)

$ErrorActionPreference = 'Stop'
$Root = $PSScriptRoot
$Home_ = $HOME
$manifest = Import-PowerShellDataFile (Join-Path $Root 'manifest.psd1')
$targets = if ($Only) { $Only } else { $manifest.Keys }

function Write-Target {
  param([string]$Path, [string]$Content)
  # CRLF per core/00-identity.md. Normalise before comparing, or -WhatIf reports a
  # change on every run purely from line endings.
  $Content = ($Content -replace "`r`n", "`n") -replace "`n", "`r`n"
  if ($WhatIf) {
    $old = if (Test-Path $Path) { Get-Content -Raw -LiteralPath $Path } else { '' }
    if ($old -eq $Content) { Write-Host "  = $Path (unchanged)" -ForegroundColor DarkGray }
    else { Write-Host "  ~ $Path (would change: $($old.Length) -> $($Content.Length) bytes)" -ForegroundColor Yellow }
    return
  }
  $dir = Split-Path -Parent $Path
  if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
  [System.IO.File]::WriteAllText($Path, $Content, [System.Text.UTF8Encoding]::new($false))
  Write-Host "  + $Path" -ForegroundColor Green
}

function Get-Stub {
  param([string]$Harness)
  $lines = @(
    "<!-- Generated by ~/agent-core/build.ps1. Edit agent-core, not this file. -->"
    ""
    "@~/agent-core/adapters/$Harness.md"
    ""
  )
  foreach ($f in $manifest[$Harness]) { $lines += "@~/agent-core/core/$f.md"; $lines += "" }
  ($lines -join "`n")
}

Write-Host "agent-core build" -ForegroundColor Cyan

if ('claude' -in $targets) {
  Write-Host "claude  -> import stub"
  Write-Target (Join-Path $Home_ '.claude/CLAUDE.md') (Get-Stub 'claude')
}

if ('omp' -in $targets) {
  Write-Host "omp     -> import stub"
  Write-Target (Join-Path $Home_ '.omp/agent/AGENTS.md') (Get-Stub 'omp')
}



Write-Host "done. run verify.ps1 to confirm each harness loads it." -ForegroundColor Cyan
