#requires -Version 7
<#
  Wires every harness to ~/agent-core.

  Claude Code and omp resolve `@~/path` imports natively (verified), so they get
  a thin stub that imports core/ directly - no generated copy to drift.
  opencode takes an `instructions` array in its config - pointed straight at core/.
  Codex has no working import (its `@RTK.md` line resolves to nothing), so its
  AGENTS.md is generated. Generated content is stamped DO NOT EDIT.
#>
[CmdletBinding()]
param(
  [switch]$WhatIf,
  [ValidateSet('claude', 'omp', 'codex', 'opencode')]
  [string[]]$Only
)

$ErrorActionPreference = 'Stop'
$Root = $PSScriptRoot
$Home_ = $HOME
$manifest = Import-PowerShellDataFile (Join-Path $Root 'manifest.psd1')
$targets = if ($Only) { $Only } else { $manifest.Keys }

function Write-Target {
  param([string]$Path, [string]$Content)
  if ($WhatIf) {
    $old = if (Test-Path $Path) { Get-Content -Raw -LiteralPath $Path } else { '' }
    if ($old -eq $Content) { Write-Host "  = $Path (unchanged)" -ForegroundColor DarkGray }
    else { Write-Host "  ~ $Path (would change: $($old.Length) -> $($Content.Length) bytes)" -ForegroundColor Yellow }
    return
  }
  $dir = Split-Path -Parent $Path
  if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
  # CRLF per core/00-identity.md
  $Content = ($Content -replace "`r`n", "`n") -replace "`n", "`r`n"
  [System.IO.File]::WriteAllText($Path, $Content, [System.Text.UTF8Encoding]::new($false))
  Write-Host "  + $Path" -ForegroundColor Green
}

function Get-Stub {
  param([string]$Harness)
  $lines = @(
    "<!-- Generated by ~/agent-core/build.ps1. Edit agent-core, not this file. -->"
    ""
    "@~/agent-core/adapters/$Harness.md"
    ""
  )
  foreach ($f in $manifest[$Harness]) { $lines += "@~/agent-core/core/$f.md"; $lines += "" }
  ($lines -join "`n")
}

function Get-Inlined {
  param([string]$Harness)
  $parts = @(
    "<!-- DO NOT EDIT. Generated by ~/agent-core/build.ps1 from core/ + adapters/$Harness.md."
    "     Change agent-core and re-run build.ps1; edits here are overwritten. -->"
    ""
    (Get-Content -Raw (Join-Path $Root "adapters/$Harness.md")).TrimEnd()
  )
  foreach ($f in $manifest[$Harness]) {
    $parts += ""
    $parts += (Get-Content -Raw (Join-Path $Root "core/$f.md")).TrimEnd()
  }
  ($parts -join "`n") + "`n"
}

# Preserve blocks another tool owns (mind writes into Codex's AGENTS.md).
function Get-ManagedBlocks {
  param([string]$Path)
  if (-not (Test-Path $Path)) { return '' }
  $raw = Get-Content -Raw -LiteralPath $Path
  $m = [regex]::Matches($raw, '(?s)<!--\s*(\S+)\s+managed[^>]*start\s*-->.*?<!--\s*\1\s+managed[^>]*end\s*-->')
  if ($m.Count -eq 0) { return '' }
  "`n" + (($m | ForEach-Object { $_.Value }) -join "`n") + "`n"
}

Write-Host "agent-core build" -ForegroundColor Cyan

if ('claude' -in $targets) {
  Write-Host "claude  -> import stub"
  Write-Target (Join-Path $Home_ '.claude/CLAUDE.md') (Get-Stub 'claude')
}

if ('omp' -in $targets) {
  Write-Host "omp     -> import stub"
  Write-Target (Join-Path $Home_ '.omp/agent/AGENTS.md') (Get-Stub 'omp')
}

if ('codex' -in $targets) {
  Write-Host "codex   -> generated (no import support)"
  $p = Join-Path $Home_ '.codex/AGENTS.md'
  $kept = Get-ManagedBlocks $p
  if ($kept) { Write-Host "  preserving externally-managed block(s)" -ForegroundColor DarkCyan }
  Write-Target $p ((Get-Inlined 'codex') + $kept)
}

if ('opencode' -in $targets) {
  Write-Host "opencode-> config instructions array"
  $cfg = Join-Path $Home_ '.config/opencode/opencode.jsonc'
  $want = @($manifest['opencode'] | ForEach-Object { "$Home_/agent-core/core/$_.md" })
  $want = , "$Home_/agent-core/adapters/opencode.md" + $want
  $raw = Get-Content -Raw -LiteralPath $cfg
  # Forward slashes: JSON-legal on Windows and needs no escaping. Backslashes here
  # produce invalid escapes (\U, \a) because $HOME already contains them.
  $json = ($want | ForEach-Object { '    "' + ($_ -replace '\\', '/') + '"' }) -join ",`n"
  $new = [regex]::Replace($raw, '(?s)"instructions"\s*:\s*\[.*?\]', "`"instructions`": [`n$json`n  ]")
  if ($new -eq $raw) { Write-Host "  ! no instructions array found - add one manually" -ForegroundColor Red }
  else { Write-Target $cfg $new }
}

Write-Host "done. run verify.ps1 to confirm each harness loads it." -ForegroundColor Cyan
